const pool = require('../src/config/db');

async function cleanUpDuplicateUsers() {
  console.log("=== STARTING DATABASE USER DEDUPLICATION & CLEANUP ===");

  // 1. Re-assign orders from secondary Khushal accounts to primary khushal.mali0506@gmail.com
  const secondaryKhushalEmails = [
    'khushal.privan06@gmail.com',
    'khushal8669382080@gmail.com',
    'neha.ingale204@gmail.com',
    'live_frontend_test_19@example.com'
  ];

  for (const secEmail of secondaryKhushalEmails) {
    try {
      await pool.query(
        `UPDATE public.orders SET user_id = 'khushal.mali0506@gmail.com' WHERE LOWER(user_id) = LOWER($1)`,
        [secEmail]
      );
    } catch (e) {
      console.warn("Orders update skipped:", e.message);
    }

    try {
      await pool.query(
        `UPDATE public.user_addresses SET user_id = 'khushal.mali0506@gmail.com' WHERE LOWER(user_id) = LOWER($1)`,
        [secEmail]
      );
    } catch (e) {}

    try {
      await pool.query(
        `DELETE FROM public.users WHERE LOWER(username) = LOWER($1) OR LOWER(emailid) = LOWER($1)`,
        [secEmail]
      );
      console.log(`Merged and removed duplicate Khushal account: ${secEmail}`);
    } catch (e) {
      console.error("Failed to delete user:", secEmail, e.message);
    }
  }

  // 2. Re-assign orders from '1' / '1@urvaah.local' to 'aakanshadhake024@gmail.com' if any
  try {
    await pool.query(
      `UPDATE public.orders SET user_id = 'aakanshadhake024@gmail.com' WHERE user_id = '1' OR user_id = '1@urvaah.local'`
    );
  } catch (e) {}

  try {
    await pool.query(
      `DELETE FROM public.users WHERE username = '1' OR LOWER(emailid) = '1@urvaah.local'`
    );
    console.log("Cleaned up duplicate account '1'");
  } catch (e) {}

  // 3. Remove test/junk accounts generated by automated test scripts
  const junkEmails = [
    'authtest_user_888@urvaah.local',
    'guest_session_9999@urvaah.local',
    'guest_temp_test_123@urvaah.local',
    'guest_test_999@urvaah.local',
    'user_login_test_7777@urvaah.local',
    'test_verifier_1790249259408@example.com',
    'testuser12345@example.com',
    'testuser99999@example.com',
    'live_frontend_test_99@example.com'
  ];

  for (const junk of junkEmails) {
    try {
      await pool.query(
        `DELETE FROM public.orders WHERE LOWER(user_id) = LOWER($1)`,
        [junk]
      );
    } catch (e) {}

    try {
      await pool.query(
        `DELETE FROM public.users WHERE LOWER(username) = LOWER($1) OR LOWER(emailid) = LOWER($1)`,
        [junk]
      );
      console.log(`Removed junk test account: ${junk}`);
    } catch (e) {}
  }

  // 4. Case-insensitive deduplication for any remaining duplicate emails in public.users
  try {
    const dupRes = await pool.query(`
      SELECT LOWER(emailid) as email, COUNT(*) 
      FROM public.users 
      GROUP BY LOWER(emailid) 
      HAVING COUNT(*) > 1
    `);

    for (const row of dupRes.rows) {
      const email = row.email;
      console.log(`Found duplicate email in database: ${email}. Keeping latest record...`);
      await pool.query(`
        DELETE FROM public.users u1
        USING public.users u2
        WHERE LOWER(u1.emailid) = LOWER(u2.emailid)
          AND u1.createdate < u2.createdate
          AND LOWER(u1.emailid) = LOWER($1)
      `, [email]);
    }
  } catch (e) {
    console.error("Deduplication error:", e.message);
  }

  console.log("=== CLEANUP COMPLETED SUCCESSFULLY ===");
  await pool.end();
}

cleanUpDuplicateUsers();
